typesense:
  apiKey: 
  apiPort: 8108
  peeringPort: 8107
  protocol: http
  cors:
    enabled: true
    domains: "http://localhost:9089"
  resetPeersOnError: true
  storage:
    size: 5Gi
    storageClassName: default
  replicas: 3
scraper:
  schedule: '*/2 * * * *'
  config: '{ "index_name": "typesense_docs", "start_urls": [], "selectors": {}, "scrape_start_urls": true,   "strip_chars": " .,;:#"}'
dashboard:
  enabled: true
  replicas: 1
