typesense:
  apiKey: 
  apiPort: 8108
  peeringPort: 8107
  protocol: http
  cors:
    enabled: true
    # 1234 is the port of the local dev server for frontend
    domains: "http://localhost:9089,https://beta.search.corp,http://localhost:1234"
  resetPeersOnError: true
  storage:
    size: 5Gi
    storageClassName: default
  replicas: 3
scraper:
  schedule: '*/2 * * * *'
  config: '{ "index_name": "typesense_docs", "start_urls": [], "selectors": {}, "scrape_start_urls": true,   "strip_chars": " .,;:#"}'
dashboard:
  enabled: true
  replicas: 1
