apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typesense.fullname" . }}-scraper-config
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.scraper.config | quote }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "typesense.fullname" . }}-scraper
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - env:
            - name: CONFIG
              valueFrom:
                configMapKeyRef:
                  key: config.json
                  name: {{ include "typesense.fullname" . }}-scraper-config
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: typesense-api-key
                  name: {{ include "typesense.fullname" . }}-api-keys
            - name: TYPESENSE_HOST
              value: {{ .Release.Name }}-svc.{{ .Release.Namespace }}.svc.cluster.local
            - name: TYPESENSE_PORT
              value: {{ required "typesense.apiPort is required" .Values.typesense.apiPort | quote }}
            - name: TYPESENSE_PROTOCOL
              value: {{ required "typesense.protocol is required" .Values.typesense.protocol }}
            image: typesense/docsearch-scraper:0.9.1
            name: typesense-scraper
            resources:
                limits:
                  cpu: 1024m
                  memory: 512Mi
                requests:
                  cpu: 128m
                  memory: 112Mi
          restartPolicy: Never
  schedule: {{ .Values.scraper.schedule | quote }}