apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "typesense.fullname" . }}-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "typesense.fullname" . }}-role
  labels:
    app.kubernetes.io/name: {{ include "typesense.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "typesense.fullname" . }}-role-binding
  labels:
    app.kubernetes.io/name: {{ include "typesense.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "typesense.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "typesense.fullname" . }}-service-account
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typesense.fullname" . }}-api-keys
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
data:
  typesense-api-key: {{ required "typesense.apiKey is required" .Values.typesense.apiKey
    | b64enc | quote }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "typesense.fullname" . }}-ts
  labels:
    app: {{ include "typesense.fullname" . }}-sts
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "typesense.fullname" . }}-sts-resolver
  replicas: {{ .Values.typesense.replicas }}
  selector:
    matchLabels:
      matchLabels:
      app: {{ include "typesense.fullname" . }}-sts
  template:
    metadata:
      labels:
        matchLabels:
        app: {{ include "typesense.fullname" . }}-sts
    spec:
      containers:
        - name: peer-resolver
          image: akyriako78/typesense-peer-resolver:v0.1.0-dev.3
          command:
            - "/opt/tspr"
            - "-namespace={{ .Release.Namespace }}"
            - "-service={{ include "typesense.fullname" . }}-sts-resolver"
        - name: typesense
          image: typesense/typesense:27.1
          command:
            - "/opt/typesense-server"
            - "--data-dir"
            - "/usr/share/typesense/data"
            - "--api-port"
            - {{ required "typesense.apiPort is required" .Values.typesense.apiPort | quote }}
            - "--api-address"
            - "0.0.0.0"
            - "--peering-port"
            - {{ required "typesense.peeringPort is required" .Values.typesense.peeringPort | quote }}
            - "--nodes"
            - "/usr/share/typesense/nodes"
            {{ if .Values.typesense.cors.enabled }}
            - "--enable-cors"
            - "--cors-domains"
            - {{ required "typesense.cors.domains is required" .Values.typesense.cors.domains }}
            {{ if .Values.typesense.resetPeersOnError }}
            - "--reset-peers-on-error"
            {{ end }}
          env:
          - name: TYPESENSE_API_KEY
            valueFrom:
              secretKeyRef:
                key: typesense-api-key
                name: {{ include "typesense.fullname" . }}-api-keys
          ports:
          - containerPort: 8108
            name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 2
          resources:
            limits:
              cpu: 1024m
              memory: 512Mi
            requests:
              cpu: 128m
              memory: 112Mi
          volumeMounts:
          - mountPath: /usr/share/typesense
            name: nodeslist
          - mountPath: /usr/share/typesense/data
            name: data
      serviceAccountName: {{ include "typesense.fullname" . }}-service-account
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 10000
      terminationGracePeriodSeconds: 300
      volumes:
      - name: nodeslist
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ required "typesense.storage.size is required" .Values.typesense.storage.size }}
      storageClassName: {{ required "typesense.storage.storageClassName is required" .Values.typesense.storage.storageClassName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense.fullname" . }}-sts-resolver
  labels:
  {{- include "typesense.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ include "typesense.fullname" . }}-sts
  ports:
  - name: http
    port: {{ required "typesense.apiPort is required" .Values.typesense.apiPort }}
    targetPort: 8108
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense.fullname" . }}-svc
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "typesense.fullname" . }}-sts
  ports:
  - name: http
    port: {{ required "typesense.apiPort is required" .Values.typesense.apiPort }}
    targetPort: 8108